apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: e2e-arm64-task
  labels:
    test-task-type: e2e-arm64-task
spec:
  taskSpec:
    steps:
    - name: verify-platform
      image: quay.io/konflux-ci/buildah-task:latest
      script: |-
        #!/bin/bash
        set -e

        if [ -e "/ssh/error" ]; then
            #no server could be provisioned
            cat /ssh/error
            exit 1
        fi
        SSH_HOST=$(cat /ssh/host)
        SSH_KEY="$HOME/.ssh/id_rsa"
        echo "ssh key path: $SSH_KEY"
        SSH_ARGS="-o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=10 -i $SSH_KEY -v"
        mkdir -p "$(dirname "$SSH_KEY")"
        curl --cacert /ssh/otp-ca -XPOST -d @/ssh/otp $(cat /ssh/otp-server) > "$SSH_KEY"
        echo "" >> "$SSH_KEY"
        chmod 0400 "$SSH_KEY"

        OS=$(ssh $SSH_ARGS $SSH_HOST uname)
        ARCH=$(ssh $SSH_ARGS $SSH_HOST uname -m)

        if [ "$OS" != "Linux" ]; then
            echo "Expected OS to be Linux, got: $OS"
            exit 1
        fi
        if [ "$ARCH" != "aarch64" ]; then
            echo "Expected architecture to be aarch64, got: $ARCH"
            exit 1
        fi
        echo "Platform verification successful: $OS/$ARCH"
      volumeMounts:
      - mountPath: /ssh
        name: ssh
        readOnly: true
    volumes:
    - name: ssh
      secret:
        optional: false
        secretName: multi-platform-ssh-$(context.taskRun.name)
    params:
    - description: The platform to build on
      name: PLATFORM
      type: string
  params:
  - name: PLATFORM
    value: linux/arm64
